/* Labels for every closed value set the settings page shows, in Korean and English.
 * A plain ES module with no DOM access, so the page and the unit tests import the same table.
 * An unknown value is shown as received. */

/** The exact members of each closed value set (the tests compare them with the server's sets). */
export const VALUE_SETS = {
  siteStatus: ["active", "needs_login", "degraded", "onboarding", "failed"],
  jobState: ["queued", "running", "awaiting_user", "succeeded", "failed", "cancelled"],
  jobKind: ["add", "repair"],
  outcomeStatus: [
    "ok",
    "empty",
    "auth_required",
    "unsupported",
    "access_denied",
    "rate_limited",
    "timeout",
    "adapter_error",
    "browser_unavailable",
  ],
  runMode: ["setup", "running", "restarting"],
  problemCode: ["passphrase_missing", "passphrase_too_short", "config_invalid", "start_failed"],
  chatgptState: ["not_configured", "external", "stopped", "starting", "ready", "failed"],
  helperRuntime: ["auto", "claude", "codex"],
  helperCheckCode: ["ok", "not_installed", "not_signed_in", "limit_reached", "failed"],
  blockKind: ["login", "captcha", "consent", "subscription", "other"],
  assistantPurpose: ["captcha", "login"],
  assistantVerdict: ["done", "failed", "needs_user"],
  assistantReason: [
    "no_saved_password",
    "verification_code",
    "question",
    "check_not_passed",
    "timed_out",
    "other",
  ],
  errorCode: [
    "invalid",
    "busy",
    "job_running",
    "locked",
    "file_unreadable",
    "tool_missing",
    "exists",
    "external",
    "not_configured",
    "config_invalid",
    "not_running",
    "bad_request",
    "unauthorized",
    "forbidden",
    "not_found",
    "conflict",
    "too_large",
    "server_error",
    "not_set",
    "unavailable",
  ],
  fieldCode: ["too_short", "empty", "unsupported_characters", "bad_format", "bad_value", "locked"],
};

const en = {
  siteStatus: {
    active: "Working",
    needs_login: "Needs you to log in",
    degraded: "Partly working",
    onboarding: "Being prepared",
    failed: "Not working",
  },
  jobState: {
    queued: "Waiting to start",
    running: "In progress",
    awaiting_user: "Waiting for you",
    succeeded: "Finished",
    failed: "Did not finish",
    cancelled: "Cancelled",
  },
  jobKind: { add: "Add site", repair: "Repair site" },
  outcomeStatus: {
    ok: "worked",
    empty: "worked, but found nothing",
    auth_required: "you need to log in to the site in the Aside browser",
    unsupported: "not supported by this site",
    access_denied: "the site refused access",
    rate_limited: "the site asked to slow down; try again later",
    timeout: "the site took too long to answer",
    adapter_error: "the site's setup has a problem (Repair may help)",
    browser_unavailable: "the Aside browser could not be reached",
  },
  runMode: { setup: "Waiting for setup", running: "Running", restarting: "Restarting" },
  problemCode: {
    passphrase_missing: "No access passphrase is set yet.",
    passphrase_too_short: "The access passphrase is too short (it needs at least 12 characters).",
    config_invalid: "A settings file has a mistake.",
    start_failed: "The program could not start.",
  },
  chatgptState: {
    not_configured: "Not set up",
    external: "Set up by hand earlier",
    stopped: "Stopped (the program is not running)",
    starting: "Starting",
    ready: "Ready",
    failed: "Stopped after errors",
  },
  helperRuntime: {
    auto: "Automatic (Claude if available, otherwise Codex)",
    claude: "Claude (Claude Code, Claude subscription)",
    codex: "Codex (ChatGPT subscription)",
  },
  helperCheckCode: {
    ok: "The helper works.",
    not_installed: "Neither Claude Code nor Codex is installed on this Mac.",
    not_signed_in: "The AI app is installed but not signed in.",
    limit_reached: "Your subscription's usage limit is reached. Try again later.",
    failed: "The check did not succeed.",
  },
  blockKind: {
    login: "Needs you to log in to the site",
    captcha: "A captcha (a test that checks a person is visiting) is in the way",
    consent: "Needs you to accept something on the site, such as its terms or cookies",
    subscription: "Needs a subscription to the site",
    other: "Needs something else from you",
  },
  assistantPurpose: {
    captcha: "Pass a bot check",
    login: "Log in",
  },
  assistantVerdict: {
    done: "Finished",
    failed: "Did not succeed",
    needs_user: "Needs you",
  },
  assistantReason: {
    no_saved_password: "No password for this site is saved in the Aside browser",
    verification_code: "The site asked for a verification code",
    question: "The site asked a question only you can answer",
    check_not_passed: "The bot check could not be passed",
    timed_out: "It took too long and was stopped",
    other: "Another problem",
  },
  errorCode: {
    invalid: "Some of what you entered is not accepted.",
    busy: "The program is restarting right now. Try again in a moment.",
    job_running: "The helper is preparing a site right now.",
    locked: "This setting is fixed outside the settings page and cannot be changed here.",
    file_unreadable: "A settings file cannot be read, so this change cannot be saved there.",
    tool_missing: "The connection tool is not installed.",
    exists: "A connection with this name already exists on this Mac.",
    external: "This connection was set up by hand; the program does not change it.",
    not_configured: "No ChatGPT connection is set up yet.",
    config_invalid: "A settings file has a mistake, so the program cannot work out its public address.",
    not_running: "The program is not running right now.",
    bad_request: "The request was not understood.",
    unauthorized: "This page is no longer signed in.",
    forbidden: "The request was refused.",
    not_found: "Not found (it may have been removed already).",
    conflict: "This cannot be done right now.",
    too_large: "What you entered is too long.",
    server_error: "Something went wrong inside the program.",
    not_set: "No access passphrase is set yet. Set one in step 1 of Getting started.",
    unavailable:
      "The clipboard of this Mac could not be used. Copy the access passphrase from where you keep it instead.",
  },
  fieldCode: {
    too_short: "Too short: use at least 12 characters.",
    empty: "This cannot be empty.",
    unsupported_characters: "Contains a character that cannot be stored, such as a line break.",
    bad_format: "Not in the expected form.",
    bad_value: "This value is not allowed.",
    locked: "Fixed outside the settings page; cannot be changed here.",
  },
};

const ko = {
  siteStatus: {
    active: "정상 작동",
    needs_login: "로그인 필요",
    degraded: "일부만 작동",
    onboarding: "준비 중",
    failed: "작동 안 함",
  },
  jobState: {
    queued: "시작 대기 중",
    running: "진행 중",
    awaiting_user: "사용자 조치 대기",
    succeeded: "완료",
    failed: "완료하지 못함",
    cancelled: "취소됨",
  },
  jobKind: { add: "사이트 추가", repair: "사이트 고치기" },
  outcomeStatus: {
    ok: "정상",
    empty: "정상이지만 찾은 내용이 없음",
    auth_required: "Aside 브라우저에서 이 사이트에 로그인해야 함",
    unsupported: "이 사이트에서 지원하지 않음",
    access_denied: "사이트가 접근을 거부함",
    rate_limited: "사이트가 요청을 줄여 달라고 함. 나중에 다시 시도하세요",
    timeout: "사이트 응답이 너무 늦음",
    adapter_error: "이 사이트 설정에 문제가 있음 (고치기로 해결될 수 있음)",
    browser_unavailable: "Aside 브라우저에 연결할 수 없음",
  },
  runMode: { setup: "설정 대기 중", running: "실행 중", restarting: "다시 시작하는 중" },
  problemCode: {
    passphrase_missing: "아직 접속 암호가 설정되지 않았습니다.",
    passphrase_too_short: "접속 암호가 너무 짧습니다 (12자 이상이어야 합니다).",
    config_invalid: "설정 파일에 잘못된 부분이 있습니다.",
    start_failed: "프로그램을 시작하지 못했습니다.",
  },
  chatgptState: {
    not_configured: "설정 안 됨",
    external: "예전에 직접 설정한 연결",
    stopped: "멈춤 (프로그램이 실행 중이 아님)",
    starting: "시작하는 중",
    ready: "준비됨",
    failed: "오류로 멈춤",
  },
  helperRuntime: {
    auto: "자동 (Claude가 있으면 Claude, 없으면 Codex)",
    claude: "Claude (Claude Code, Claude 구독)",
    codex: "Codex (ChatGPT 구독)",
  },
  helperCheckCode: {
    ok: "도우미가 정상 작동합니다.",
    not_installed: "이 Mac에 Claude Code도 Codex도 설치되어 있지 않습니다.",
    not_signed_in: "AI 앱은 설치되어 있지만 로그인되어 있지 않습니다.",
    limit_reached: "구독 사용 한도에 도달했습니다. 나중에 다시 시도하세요.",
    failed: "확인에 실패했습니다.",
  },
  blockKind: {
    login: "사이트에 로그인해 주어야 함",
    captcha: "캡차(사람이 방문했는지 확인하는 테스트)가 가로막고 있음",
    consent: "사이트에서 약관이나 쿠키 같은 것에 동의해 주어야 함",
    subscription: "사이트 구독이 필요함",
    other: "그 밖의 조치가 필요함",
  },
  assistantPurpose: {
    captcha: "봇 검사 통과",
    login: "로그인",
  },
  assistantVerdict: {
    done: "완료",
    failed: "성공하지 못함",
    needs_user: "사용자 조치 필요",
  },
  assistantReason: {
    no_saved_password: "Aside 브라우저에 이 사이트의 비밀번호가 저장되어 있지 않음",
    verification_code: "사이트가 인증 코드를 요구함",
    question: "사이트가 사용자만 답할 수 있는 질문을 함",
    check_not_passed: "봇 검사를 통과하지 못함",
    timed_out: "시간이 너무 오래 걸려 멈춤",
    other: "그 밖의 문제",
  },
  errorCode: {
    invalid: "입력한 내용 중 받아들일 수 없는 것이 있습니다.",
    busy: "지금 프로그램이 다시 시작하는 중입니다. 잠시 후 다시 시도하세요.",
    job_running: "지금 도우미가 사이트를 준비하고 있습니다.",
    locked: "이 설정은 설정 페이지 밖에서 정해져 있어 여기서 바꿀 수 없습니다.",
    file_unreadable: "설정 파일을 읽을 수 없어 이 변경을 저장할 수 없습니다.",
    tool_missing: "연결 도구가 설치되어 있지 않습니다.",
    exists: "이 이름의 연결이 이 Mac에 이미 있습니다.",
    external: "직접 설정한 연결이라 프로그램이 바꾸지 않습니다.",
    not_configured: "아직 ChatGPT 연결이 설정되지 않았습니다.",
    config_invalid: "설정 파일에 잘못된 부분이 있어 프로그램의 공개 주소를 알 수 없습니다.",
    not_running: "지금 프로그램이 실행 중이 아닙니다.",
    bad_request: "요청을 이해하지 못했습니다.",
    unauthorized: "이 페이지의 로그인이 끝났습니다.",
    forbidden: "요청이 거부되었습니다.",
    not_found: "찾을 수 없습니다 (이미 삭제되었을 수 있습니다).",
    conflict: "지금은 할 수 없습니다.",
    too_large: "입력한 내용이 너무 깁니다.",
    server_error: "프로그램 내부에서 문제가 생겼습니다.",
    not_set: "아직 접속 암호가 정해져 있지 않습니다. 시작하기의 1단계에서 정하세요.",
    unavailable: "이 Mac의 클립보드를 쓸 수 없습니다. 접속 암호를 보관해 둔 곳에서 직접 복사하세요.",
  },
  fieldCode: {
    too_short: "너무 짧습니다. 12자 이상으로 입력하세요.",
    empty: "비워 둘 수 없습니다.",
    unsupported_characters: "저장할 수 없는 문자(예: 줄바꿈)가 들어 있습니다.",
    bad_format: "형식이 맞지 않습니다.",
    bad_value: "허용되지 않는 값입니다.",
    locked: "설정 페이지 밖에서 정해져 있어 여기서 바꿀 수 없습니다.",
  },
};

export const LABELS = { en, ko };

/** The label of `value` in the set `set`, or the value itself when the table has none. */
export function label(lang, set, value) {
  const table = (LABELS[lang] ?? LABELS.en)[set];
  if (table && Object.prototype.hasOwnProperty.call(table, value)) return table[value];
  return value === null || value === undefined ? "" : String(value);
}
